name: build

on:
  push:
    branches:
      - '*'
      - '!release-*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

  create-release:
    runs-on: ubuntu-latest

    steps:
      - id: release
        uses: GoogleCloudPlatform/release-please-action@v1.5.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: node
          package-name: ace-custom-element

      # push to npm if release-please created a release
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}

      # push to bit.dev if release-please created a release
      - run: npm install --global bit-bin
        if: ${{ steps.release.outputs.release_created }}
      - name: bit.dev configuration
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{secrets.BIT_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
      - name: publish to bit.dev
        run: |
          bit init
          bit add --id ace-custom-element dist/*
          bit tag --all `node scripts/version.js`
          bit export socsieng.ace-custom-element
        if: ${{ steps.release.outputs.release_created }}
